image: hyperized/ansible-docker-image:ubuntu1404-current

before_script:
  - mkdir -p /etc/ansible/roles/`basename "$PWD"` && cp -R * /etc/ansible/roles/`basename "$PWD"`

stages:
  - yaml
  - syntax
  - execution

# Verify Syntax is A OK.
yaml_lint:
  stage: yaml
  script:
    - yaml-lint -i -q .

syntax_check:
  stage: syntax
  script:
    - ansible --version
    - ansible-playbook --syntax-check tests/main.yml

syntax_check_devel:
  stage: syntax
  image: hyperized/ansible-docker-image:ubuntu1404-devel
  script:
    - ansible --version
    - ansible-playbook --syntax-check tests/main.yml

# Check actual execution
execution_current:
  stage: execution
  script:
    - ansible --version
    - ansible-playbook tests/main.yml --connection=local
    - >
      ansible-playbook tests/main.yml --connection=local
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

execution_devel:
  stage: execution
  image: hyperized/ansible-docker-image:ubuntu1404-devel
  script:
    - ansible --version
    - ansible-playbook tests/main.yml --connection=local
    - >
      ansible-playbook tests/main.yml --connection=local
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)